### ISSUE TITLE
Pause song until sample rate changes

### ISSUE THREAD

**Issue by apastuszak** [vincentneo/LosslessSwitcher#1]
I don't know if this is possible, but could you pause the song, change the sample rate and un-pause the song to avoid the hickup with the sample rate change?

**Comment by vincentneo** [comment]
Can't think of a way for that to be possible at present moment.

The app works by reading the log which Apple Music app produces. Every time the next song starts playing, the Music app logs the sample rate down.

LosslessSwitcher reads these logs periodically and adjusts the device. 

Hence, with the current method, there is no actual interaction with the Music app, and thus LosslessSwitcher can't control things like pausing.

Maybe one day I will find a way. Hopefully.

**Comment by apastuszak** [comment]
I had something odd happen today. I was listening to the song "Comfortably numb" by Pink Floyd.  The sample rate changed from 44.1 to 96. Then 5 minutes into the song, it changed again to 192 kHz.

Also, whenever the sample rate changes, it always goes to 48 kHz and then to the sample rate the song is encoded in.

I have to assume that the 48 kHz thing is just how CoreAudio works.

Apple needs to make an API, so we can incorporate Apple Music into an app that switch sample rate on the fly.

Thanks for writing this. It's very impressive.

**Comment by vincentneo** [comment]
yup the issue is tracked as #3 right now. 

Hopefully WWDC22's next macOS version would have this lossless switching feature in the Music app itself. :)

**Comment by vincentneo** [comment]
Good news: I think I might have found a way to trigger pauses :)
