### ISSUE TITLE
Doesn't work macbook m1 pro ifi zen dac apple music

### ISSUE THREAD

**Issue by nazarp-panoply** [vincentneo/LosslessSwitcher#109]
<img width="520" alt="Screenshot 2023-09-13 at 13 20 41" src="https://github.com/vincentneo/LosslessSwitcher/assets/131145939/3bb4035a-e986-44b1-8731-77613652e3ac">
13.5.2 (22G91) macos ventura, ifi zen dac2, apple music, coldplay x&y album
it should be 192khz, but app switcher only to 48 khz.

**Comment by bonifaido** [comment]
Do you have **Bit Depth Switching** enabled?

**Comment by nazarp-panoply** [comment]
UPDATE: works for another coldpaly album --- a rush of blood to the head, which is also 192khz. Maybe log format in the x&y album is different, maybe check it or close the ticket. Thanks for the app!

**Comment by nazarp-panoply** [comment]
> Do you have **Bit Depth Switching** enabled?

yes

**Comment by nazarp-panoply** [comment]
<img width="257" alt="Screenshot 2023-09-13 at 13 28 43" src="https://github.com/vincentneo/LosslessSwitcher/assets/131145939/e812c725-783e-498f-a442-44822266739e">
Maybe I just had to restart pc after installation, because now both works. Will create a separate ticket if encounter this behaviour in the future again. Thanks!
