### ISSUE TITLE
No Sample and Bit rate switching with imported ALAC and WAV files.

### ISSUE THREAD

**Issue by Neymster** [vincentneo/LosslessSwitcher#120]
Looks like Lossless Switcher is only working with Apple Music streamed and/or downloaded files. But once you import ALAC or WAV files nothing seems to happen.
<img width="934" alt="Screenshot 2023-12-14 at 8 58 12 PM" src="https://github.com/vincentneo/LosslessSwitcher/assets/153882026/4bbab7ed-5ebd-4723-9936-4e40503d193a">
<img width="1013" alt="Screenshot 2023-12-14 at 8 58 57 PM" src="https://github.com/vincentneo/LosslessSwitcher/assets/153882026/d596337d-223a-43c1-b1e1-5f738b806d6c">
<img width="998" alt="Screenshot 2023-12-14 at 9 01 03 PM" src="https://github.com/vincentneo/LosslessSwitcher/assets/153882026/a786836b-f386-41e2-9c8d-b46585445f7f">
<img width="1018" alt="Screenshot 2023-12-14 at 9 01 18 PM" src="https://github.com/vincentneo/LosslessSwitcher/assets/153882026/fe6193cb-8f0d-4aba-ba32-b9745606615f">

**Comment by MasterRahool** [comment]
Always has been

https://github.com/vincentneo/LosslessSwitcher/discussions/74
