### ISSUE TITLE
Support for older macOS releases

### ISSUE THREAD

**Issue by odedia** [vincentneo/LosslessSwitcher#122]
I have an old Mac Mini 2012 as a play server in my home, I'm sure that's a common use case for many. Sadly, the app does not support macOS Catalina which is the latest it supported. Any idea if it can be backported to earlier versions?

**Comment by MasterRahool** [comment]
Quick question, but does the Catalina version of Apple Music support Lossless audio? Lossless came out in 2021 and Catalina was 2019, and I didnt see any Supplemental Updates to add it when I looked up version history, just security patches

**Comment by odedia** [comment]
You are correct, I just checked... It is locked to AAC. I've been using Audirvana so far and I'm beginning to dislike the experience.
Well, I guess it's time for OpenCore Legacy Patcher and a newer OS release on this hardware :)
Thanks for the great app!

**Comment by vincentneo** [comment]
Yup lossless was introduced with macOS 11.4, so no older version of macOS including Catalina supports it

**Comment by incredibleole** [comment]
Hello, I have the same problem. I don't unterstand what you mean with the introduction of lossless in 11.4. Apple Lossless has been support in ancient iPods and I listen to losses files in catalina music app. I hesitate to use open core, because I don't want to make the system slower as necessary. The system works very well as a mediacenter as it is.

**Comment by odedia** [comment]
Good point, iTunes worked with lossless/hi-res forever, I was specifically referring to lossless from the Apple Music service, not for local content.

**Comment by vincentneo** [comment]
>  I don't unterstand what you mean with the introduction of lossless in 11.4. 

I mean Apple Music Lossless. [(source)](https://www.imore.com/lossless-apple-music-needs-ios-146-ipados-146-macos-114-and-tvos-146) This app is meant for Apple Music users only, not local files.
