### ISSUE TITLE
music is 24bits even if it's 16 bits

### ISSUE THREAD

**Issue by olivierfz6** [vincentneo/LosslessSwitcher#129]
Hello, I have a Mac mini m1 with Sonoma 14.3.1. It works great, but I have noticed that when I listen to music with Apple Music, the audio and midi configuration app is in 24bits whereas the music is in lossless 16bits. The rates (44.1kHz) is good.
Also, I have noticed that I don't have 16 bits in the audio and midi configuration app, maybe it is the issue ? 
I use a TEAC UD-501 DAC.
You'll find attached the screen
![Capture d’écran 2024-02-18 à 14 32 30](https://github.com/vincentneo/LosslessSwitcher/assets/160404351/20168f82-2c77-4b26-aa1b-8594ddf311e5)

**Comment by vincentneo** [comment]
If Audio MIDI Setup shows no 16 bit, that means that your device does not support 16 bit.
