### ISSUE TITLE
request: allow to choose the device to set the sample rate for

### ISSUE THREAD

**Issue by bsphere** [vincentneo/LosslessSwitcher#13]
I'm using [eqmac](https://eqmac.app/)  and LosslessSwitcher is changing the sample rate of the eqmac audio device, i would like it to change it for the actual output device (which also changes the sample rate for the eqmac device if i do it manually from Audio MIDI Setup).

**Comment by riclib** [comment]
Same request for a different reason.
<img width="627" alt="CleanShot 2022-05-21 at 22 42 28@2x" src="https://user-images.githubusercontent.com/644724/169666831-af531c06-6748-44e4-b180-f63f73435503.png">
I have two different dacs connected to my mac, one of which is dedicated just to apple music, so it could switch sample rates there without interfering with other apps.
But lossless switcher is ofcourse changing the default audio device 😀
<img width="188" alt="CleanShot 2022-05-21 at 22 44 08@2x" src="https://user-images.githubusercontent.com/644724/169666897-19f2c987-4160-47b4-a620-ac5ef4d06563.png">

**Comment by vincentneo** [comment]
Hi all, please refer to beta 4 of v1.1 (https://github.com/vincentneo/LosslessSwitcher/releases/tag/1.1.0-beta4) for an implementation of selectable audio device!

Thank you!
