### ISSUE TITLE
Does not detect track switch when playlist progresses to next track.

### ISSUE THREAD

**Issue by AbodhGawande** [vincentneo/LosslessSwitcher#17]
Works great when manually performing Play/Pause/Next track but when playing a playlist with different bit rate tracks, it fails to register that the playback has progressed to next track and remains on previous track's bitrate

**Comment by vincentneo** [comment]
Hi @AbodhGawande, just to notify you that beta 4 of this app has been released, and one of the included new implementation should reduce or resolve this playlist issue.

Please do have a look, and if there's any regression or feedback, please do let me know. Thank you!
