### ISSUE TITLE
Bit depth not changing

### ISSUE THREAD

**Issue by resignationinfinite** [vincentneo/LosslessSwitcher#2]
On my 2021 16" MacBook Pro with M1 Pro chip, the app will change the bitrate but not the depth.

Thanks for writing this app!

**Comment by vincentneo** [comment]
Yup that's the current situation. The public API Core Audio, does not seem to have a way to read/write bit depth. 

Might have to look into a private API for this, to gain control of it just like in Audio MIDI Setup.

**Comment by rorybramley** [comment]
This is a dealbreaker for me. No point having automatic sample rate switching for "bit-perfect playback" if the bit-depth is still off.

**Comment by AmazingTechGeek-O** [comment]
To the person above, the MacBook internal speakers cannot be changed from 32-bits. This is a great start to an app in place of a function Apple should have included in MacOS Apple Music; other external devices changing bit depth with this app require additional programming, which may or may not be implemented.

Have some gratitude. Thank you vincentneo.

**Comment by rorybramley** [comment]
> To the person above, the MacBook internal speakers cannot be changed from 32-bits. This is a great start to an app in place of a function Apple should have included in MacOS Apple Music; other external devices changing bit depth with this app require additional programming, which may or may not be implemented.
> 
> Have some gratitude. Thank you vincentneo.

I disagree. The whole purpose of trying to get bit-perfect playback is to optimise for external hardware that actually makes use of hi-res music. This still doesn't fix the issue so I don't see why I need to be "grateful" for a tool that doesn't work properly. As noted elsewhere there are still many bugs

**Comment by AmazingTechGeek-O** [comment]
> > To the person above, the MacBook internal speakers cannot be changed from 32-bits. This is a great start to an app in place of a function Apple should have included in MacOS Apple Music; other external devices changing bit depth with this app require additional programming, which may or may not be implemented.
> > Have some gratitude. Thank you vincentneo.
> 
> I disagree. The whole purpose of trying to get bit-perfect playback is to optimise for external hardware that actually makes use of hi-res music. This still doesn't fix the issue so I don't see why I need to be "grateful" for a tool that doesn't work properly. As noted elsewhere there are still many bugs

You are owed nothing.

The creator doesn’t work for Apple (not you) and doesn’t owe you anything. This isn’t an app you pay for and Vincent is asking for help; it’s a project based app with issues being worked out like any other app in development. I stand by what I said, have gratitude.

You don’t like it? Give feedback and move on with your life. Deal breaker? You would have to make be making a deal here for it to even break. But if you’re owed nothing from this app, then I guess it can’t be broken then. Stay blessed!

**Comment by ashafai** [comment]
I completely agree with AmazingTechGeek-O. It's rather ridiculous to make such an unnecessary and unhelpful comment. If you don't appreciate someone's effort and don't like a [free to you] product, don't use it, and politely go away. 

That said, in using the app, my Chord Hugo TT2 does show the sample rate changing, but I would like to know how was it discovered that the depth rate was not being impacted as it should have been?

Thank you.

**Comment by KutuzovGambit** [comment]
> That said, in using the app, my Chord Hugo TT2 does show the sample rate changing, but I would like to know how was it discovered that the depth rate was not being impacted as it should have been?
> 
> Thank you.

Just check Audio MIDI app, you can see the bit depth not change with Apple Music tracks.

**Comment by deftdriver** [comment]
This is not a problem!  Playback of 16-bit audio at 24-bits does not affect sound quality.  The extra bits over 16 are padded with 0's thus not affecting anything.  Only the sample rate matching is important in the context of audio being sent to a DAC.

**Comment by vincentneo** [comment]
Please try out Beta 8!

**Comment by MDGSC** [comment]
I think it's pointless if you use 32bit Asynchronous USB DAC, at least every 32bit USB DAC I use bit depth is not changeable for user , only 24bit DAC can change bit depth ,  and I think it is not a problem to use upper depth for audio, if you use eqMac or something like this the loopback device is force to 32bit , in this case ,force bit depth sync to music means nothing .

**Comment by MDGSC** [comment]
> I think it's pointless if you use 32bit Asynchronous USB DAC, at least every 32bit USB DAC I use bit depth is not changeable for user , only 24bit DAC can change bit depth , and I think it is not a problem to use upper depth for audio, if you use eqMac or something like this the loopback device is force to 32bit , in this case ,force bit depth sync to music means nothing .

And with this build lossless switcher keep trying to change device's bit depth in every song, but can't change it because it not changeable for user , so I'll skip this build.

**Comment by lordmanuu** [comment]
I am using a 2021 MacBook Pro (apple silicon), My DAC is the IFI Go Bar. Bit depth switching sometimes won't happen, or update to the correct Khz of the lossless music, Other than the occasional glitch, It's an amazing application!

**Comment by vincentneo** [comment]
Bit depth switching is supported in release v1.1.
