### ISSUE TITLE
Bitrate switches back to 48Khz

### ISSUE THREAD

**Issue by sydsyd** [vincentneo/LosslessSwitcher#3]
When choosing a new track or skipping to next track, the bit rate switches back to 48kHz even if the currently playing and next track is at a higher bitrate.
Suggest you keep the bitrate the same unless the new track is different from currently playing track.
- this is on an M1 Pro MacBook Pro

**Comment by MasterRahool** [comment]
Same issue. Trying to pay Fire it Up by Rick James, which is a 96k album. It switches rather to 48k, then after some time it realizes it should be 96k. Skipping to the next track results in the same issue, it flops back to 48k.

Seems to be an issue with any Lossless track over 44? Because when I click on 44.1 albums it changes correctly, but 88 turns into 48

**Comment by sydsyd** [comment]
What DAC are you using?
I’m using a Chord Hugo 2

**Comment by MasterRahool** [comment]
> What DAC are you using? I’m using a Chord Hugo 2

Schiit Bifrost 2

**Comment by vincentneo** [comment]
Upon further inspection of the Music app log outputs, it seems like it prints that it will:
play a lossy 48kHz track -> lossless 48kHz -> actual lossless track with actual sample rate.

Will be looking at other messages to see if there's a way to identify if there's a message right before the actual sample rate message

**Comment by vincentneo** [comment]
Hi all, 

if you are feeling adventurous, please do try the latest beta build: https://github.com/vincentneo/LosslessSwitcher/releases/tag/1.1.0-beta1

and report back if there's any unexpected issues that aren't listed in the release notes.

Thanks!

**Comment by MasterRahool** [comment]
> Upon further inspection of the Music app log outputs, it seems like it prints that it will: play a lossy 48kHz track -> lossless 48kHz -> actual lossless track with actual sample rate.
> 
> Will be looking at other messages to see if there's a way to identify if there's a message right before the actual sample rate message

i wasnt going to bring this up initially, since it's 3rd party software, but I use an EQ which copies the rate of my DAC. The software is Boom3d if that matters.

Anyway, I had given up using it with LosslesSwitcher because every track, or track selection, starts with 3-4 "skips". Maybe thats related to what we're seeing above, the sample rate changing changing initially a few times?

**Comment by vincentneo** [comment]
> Maybe thats related to what we're seeing above, the sample rate changing changing initially a few times?

Yes. the beta release aims to fix that, and also to fix #8 (prevent next track, same sample rate switching) eventually.

**Comment by MasterRahool** [comment]
> 

trying the beta now, having a number of issues, initially it wasnt changing at all. Closed things off a few times and this is what I'm experiencing:

- hi-res streams (ie, 96k) are stuck at 48k
- hi-res _downloads_ are working
- 44.1 seems to be working but noticing skipping around 2 seconds in (I guess it's pausing to change, notices there is no change to make, and continues?) (same with higher res tracks, so its just an annoying quirk in general)

bonus:
- seems to be working with my EQ now for the most part, same symptoms as above, but the "3-4 skips before playing" issue I wrote earlier today is gone

**Comment by vincentneo** [comment]
Thanks for the in depth info @MasterRahool!

**Comment by julianhoelz94** [comment]
I seem to have a similar issue on my MacMini M1, which I use together with a CambridgeAudio DacMagicPlus. Instead of switching to 48 kHz, at the beginning of a song the bitrate always switches to 44.1 kHz, which is the lowest bit rate the DAC supports.

I have tried this with the version 1.1-beta5.
