### ISSUE TITLE
Beta 5 not worky

### ISSUE THREAD

**Issue by MasterRahool** [vincentneo/LosslessSwitcher#30]
Hate to bring this assessment but I switched from Beta 4 to 5 and...it didnt work at all, just stuck on whatever my last setting was. Not a single track triggered a bitrate switch. I re-downloaded beta 4 and it immediately 'worked' again (other issues notwithstanding) 

Currently using M1 macbook on MacOS Ventura

**Comment by vincentneo** [comment]
Thanks for updating me on this! Must have been the AppleScript addition for local files breaking this. 

Side note: the fact that you’re using this on (I guess beta 6/7?) of Ventura, suggests that native Music app doing what this project does, by itself, won’t be a reality for yet another year 🥲

**Comment by vincentneo** [comment]
Since v1.1 is out now, I guess I can close this! Feel free to open new issues when needed!
