### ISSUE TITLE
Selectable audio device defaulting

### ISSUE THREAD

**Issue by MasterRahool** [vincentneo/LosslessSwitcher#32]
This may just be because I use an EQ software and a weird glitch, but this feature reverts to Default Device constantly. For example, if I open MIDI Setup to verify a bitrate, my selected device will reset. Sometimes I look up and see it just randomly went back to default from my chosen DAC. Really wish there was a way to make it stick to my DAC.

v1.1 build 7/beta 4

**Comment by vincentneo** [comment]
@MasterRahool does macOS also revert to another device also? Or just LosslessSwitcher?

**Comment by MasterRahool** [comment]
> @MasterRahool does macOS also revert to another device also? Or just LosslessSwitcher?

Technically only LosslessSwitcher is changing from selected to default, but I suspect the OS is rechecking the device in the background

i did a test, with the EQ software killed so eliminate that variable. LosslessSwitcher is selected to my DAC, and in the OS I'm outputting to my display. I toggle back n forth between my dac and display as outputs, and LS stays on selected (my dac). I then click on Airplay, and LS switches to default device. 

I think something similar is happening with my EQ, the OS rechecks and routes to the EQ (a virtual device) and then LS stumbles back to Default from Selected
<img width="588" alt="Screenshot 2022-11-04 at 12 51 07 PM" src="https://user-images.githubusercontent.com/104704170/200031674-b60f2741-b1c3-453f-9357-a879156d85ac.png">

**Comment by vincentneo** [comment]
Probably not easy to fix, I reckon.

**Comment by MasterRahool** [comment]
> Hi @MasterRahool,
> 
> Please try build 9 (https://github.com/vincentneo/LosslessSwitcher/releases/tag/1.1.0-beta6), and update me if this helps. Thanks!

Sorry to report but it didnt work at all. Wasn't switching at all for me. I was constantly trying different bitrate tracks and then checking switcher to see if the device or rate changed, and I did notice it was now (sometimes) selecting both my DAC and default at once

<img width="659" alt="Screenshot 2022-11-16 at 11 07 01 AM" src="https://user-images.githubusercontent.com/104704170/202233123-31e6d3d0-e694-499e-a0ca-9cb4ebf2d609.png">

but even then it wasn't switching properly. I even had an issue where I finally got it to go from 44 to 192, then I selected another 192k track and it went back to 44.1 as if it only liked some 192 albums and not others :/

<img width="789" alt="Screenshot 2022-11-16 at 11 08 17 AM" src="https://user-images.githubusercontent.com/104704170/202233595-84e015ef-8cc2-46b0-899a-03e3f9a837ff.png">

I've personally gone back to Build 7 so the switching part at least functions fine (I [noted build 8](https://github.com/vincentneo/LosslessSwitcher/issues/30#issue-1373368302) was giving me a headache)

**Comment by vincentneo** [comment]
@MasterRahool,

Please try out build 10, which is basically build 9, without the #30 build 8 AppleScript addition, so that we could narrow down the issue, in case its brought in by #30.

It is in the same beta 6 link.

**Comment by MasterRahool** [comment]
> @MasterRahool,
> 
> Please try out build 10, which is basically build 9, without the #30 build 8 AppleScript addition, so that we could narrow down the issue, in case its brought in by #30.
> 
> It is in the same beta 6 link.

Functionally its operating like build 7 for me, that is, switching fine when my device is selected

On first run I noticed the same "dac and default both checked" 

<img width="681" alt="Screenshot 2022-11-16 at 11 47 55 AM" src="https://user-images.githubusercontent.com/104704170/202243970-42ebfa52-36b1-4e4f-bb02-cccc8444ec3b.png">

As for staying on the selected device, I found no difference. If I opened up MIDI, it would switch from my dac back to default (which is my EQ), and tracks would stop switching until I manually selected the DAC again

I tested again with the EQ software off like in my previous description, and then changed my system audio to an Airplay device, and LosslessSwitcher also changed to Airplay from my DAC (ie, to system default and didnt stay on my dac)

<img width="606" alt="Screenshot 2022-11-16 at 11 57 12 AM" src="https://user-images.githubusercontent.com/104704170/202244753-b2cdacc7-ebe9-4ab6-bd67-d7b30956e914.png">

but had check boxes on both default and dac again

**Comment by MasterRahool** [comment]
RE: Build 11

Only testing on my laptop right now, but doing the toggle test between macbook speakers (selected) and multiple airplay (default) devices, and so far it's working fine. Going into MIDI settings didnt reset it to default like before, and the macbook speakers were changing properly even with MIDI open.

<img width="769" alt="Screenshot 2022-11-17 at 1 14 16 AM" src="https://user-images.githubusercontent.com/104704170/202370502-45ac51df-ee3c-4f37-be61-a7d48c42cc45.png">

And this is with my EQ running, so it competing for attention isnt changing anything. 

I'll update if there's a behavior change with my DAC

**Comment by MasterRahool** [comment]
- Killing the EQ (while its selected) and checking LLS, its *still* selected as the device. Rebooting the EQ and it stays selected proper. Figure this is the equivalent of the 'unplugging it' test you wanted. 
- Tried toggling devices to make it screw up, not biting, no errors
- Unplugged my monitor/dac (thunderbolt chaining everything) and it stopped selecting the dac (because it wasnt plugged in). Plugging the cable back in and LLS goes back to having my dac selected. 


So @vincentneo so far looking solid, can't find an issue

**Comment by vincentneo** [comment]
Glad to hear! 🙂
