### ISSUE TITLE
LosslessSwitcher needs admin privileges?

### ISSUE THREAD

**Issue by macuserguru** [vincentneo/LosslessSwitcher#37]
I use Foobar2000 on an M1 MacMini under Ventura 13.0 
I want to get an bit-perfect output - but Foobar2000 use the Mac Audio-MIDI-Settings.

I got an hint from Foobar2000 forum to use the LosslessSwitcher.

But I get this message:
"LosslessSwitcher requires Administrator privileges in order to detect each song's lossless sample rate in the Music app."

My working user on the Mac have no Administrator privileges, I do that for better security.

What should I do?

Have anyone tested LosslessSwitcher on an M1 ARM CPU Mac too?

**Comment by vincentneo** [comment]
> I use Foobar2000 on an M1 MacMini under Ventura 13.0

LosslessSwitcher is really only designed for the Apple Music app so far, not sure how Foobar2000 on the Mac works, and definitely not a supported use case right now.

> LosslessSwitcher requires Administrator privileges in order to detect each song's lossless sample rate in the Music app.

Yes. LosslessSwitcher works by monitoring the system logs. Apple requires Admin privileges for third party apps like LosslessSwitcher to access it.

> Have anyone tested LosslessSwitcher on an M1 ARM CPU Mac too?

Yup! While I personally do not have an Apple Silicon Mac yet, lots of users have reported success on their machines. You can see this on the home page, where there's a table of tested devices.

**Comment by macuserguru** [comment]
I installed three music player on my Mac.
Fidelia, Audirvana Studio, Foobar2000.
Fidelia, Audirvana Studio have the pass-through feature too. I think it gives this feature in the macOS soundsystem too.
Fidelia, Audirvana Studio have equalizer too -  it seems that a part of macOS soundsystem too. 
Foobar2000 primilary designed for Windows, so don't have this needed middleware driver - and use only the settings in Audio-MIDI-Setup.

**Comment by vincentneo** [comment]
As LosslessSwitcher's detection method requires administrative rights, I will close this issue, since there's not much that could be done, unless an alternate detection method is found.
