### ISSUE TITLE
Apple Music Dropouts 

### ISSUE THREAD

**Issue by jimmyvail** [vincentneo/LosslessSwitcher#5]
Great work on this Switcher . I’m using a current MacMini M1 . I am occasionally getting dropouts during a song being played . I use this Mini just for music .

**Comment by vincentneo** [comment]
I believe this issue is linked to #3

**Comment by jimmyvail** [comment]
Hi Vincent . Great job . You may be right  . I will check this as I typically listen 8 feet from the dac so I will get close to the dac to verify .

Thanks for your work.

Jim
