### ISSUE TITLE
request: allow to choose multiple devices to set the sample rate

### ISSUE THREAD

**Issue by MDGSC** [vincentneo/LosslessSwitcher#50]
Thank you for release this amazing app to solve sample rate problem for Apple Music.

I'm now using BlackHole to loopback audio to AudioUnit Host app like AULab and Hosting AU to use batter EQ plug-in and send the sound to USB DAC，but at now time LosslessSwitcher can only change one device's sample rate at one time, can you add  multiple devices sample rate change function ?

**Comment by vincentneo** [comment]
Hi @MDGSC,

Thanks for writing in. 

Am I right to say that you wish for all/a selectable few audio devices to be switch simultaneously?

**Comment by MDGSC** [comment]
@vincentneo Yes , usually AUHost app have there own audio engine so bit depth is not a problem, but both input/output devices’ sample rate need to switch simultaneously to match AppleMusic’s sample rate so system don’t need to resample audio single .

**Comment by MDGSC** [comment]
Okay, I found solution at Audio MIDI Setup app , just use "Create Multi-Output Device" to group devices want to change sample rate simultaneously and don't use it for output , and let LosslessSwitcher to change multi-output device's sample rate then it will change simultaneously.

**Comment by MDGSC** [comment]
Uh...I'm sorry to bother you @vincentneo , but can you test LosslessSwitcher is working good with Multi-Output Device?
in my case it worked a little time but now working at all , thank you and have a nice day.

**Comment by vincentneo** [comment]
@MDGSC I haven't test the Multi-Output Device setting that you mentioned yet (only saw this comment now), but from the Audio MIDI app alone, I can't tell if it handles all the selected device's sample rate or locks them at a fix rate, etc.
