### ISSUE TITLE
Opening YouTube in Safari changes Sample Rate

### ISSUE THREAD

**Issue by DeckHeadFi** [vincentneo/LosslessSwitcher#51]
Seems like Beta 6, build 11 has this issue - 
- if I'm playing music on music app on my Macbook air, then I open Safari and go to YouTube.com - it seems like losslesswitcher is reading YouTube somehow and changing the sample rate. Even if I have Safari completely muted. So not sure if it's just YouTube or there are certain situations where losslesswitcher is reading music/sound from places other than the music app. 
- I could also see someone actually liking this feature if they play YouTube and losslessswitcher is reading YouTube sample rate correctly (I'm not sure if it is or not). 
- Suggestion: Allow for Music App and YouTube to have separate sample rate reading capabilities where you can have them both on at same time (switches correctly) or only have one on at a time. For example: Option 1) both Music App and YouTube Sample Rate changes automatically when you go back and forth. Option 2) Music App on, YouTube off. Option 3) YouTube on, Music app off.

**Comment by MasterRahool** [comment]
I've noticed this happen once but wasn't sure how I triggered it / haven't been able to repeat it

**Comment by vincentneo** [comment]
Please try out v1.1 build 12 / beta 7, thank you!

**Comment by DeckHeadFi** [comment]
Awesome. I will try this soon and report back if any issues. Makes sense to restrict this to Music app users. Thank you so much for taking the time and doing such a great job on this. I love Apple Music, but this is the feature that I appreciate so much!!

**Comment by MasterRahool** [comment]
> Please try out v1.1 build 12 / beta 7, thank you!

while your notes do say that local detection may cause it to not work like before, just confirming that yeah....no worky (once i disable it it starts working again)

as for app detection, i played a 192k track (local disabled), it was fine, then paused and opened up safari, opened youtube, and it didnt change to 48k
