### ISSUE TITLE
Sample rate switching one minute early

### ISSUE THREAD

**Issue by kuobakuoba** [vincentneo/LosslessSwitcher#6]
Hi.
I'm on M1 MacBook Air MacOS 12.3.1, and I found out the sample rate would switch to the next song's sample rate about 1 min too early. Let's say I'm playing a 48kHz track with a 96kHz one on queue. It'll switch to 96kHz while the current 48kHz one still has one minute to go. Wondering if anyone else is experiencing the same issue.

**Comment by vincentneo** [comment]
I believe this issue is the same as #3

**Comment by AmazingTechGeek-O** [comment]
I downloaded the pre-release. Will give feedback later. Really grateful you created this app. It's a real miracle and I do hear the differences in the frequency range in my studio space. :)
