### ISSUE TITLE
Build 14 still switches Bit Depth when disabled

### ISSUE THREAD

**Issue by MasterRahool** [vincentneo/LosslessSwitcher#79]
So been beta'ing Build 14 for the past day and find it constantly changes my bit depth, even with it unchecked. Trying turning it on and off to see if it made a difference, and it did not.

First noticed when I opened up Audio Devices and found it was set to 16-bit (instead of my usual 32-bit). Tried manually setting 32-bit several times and selected various different bitrates to trigger a switch, and every time it changed the depth along with it. As one final test before posting this, was listening to a 24/48 track, manually switched to 32/48, then played a 44.1/16 track...and LLS switched to 44/16

_Setting my daily back to Build 11 for now_

**Comment by vincentneo** [comment]
yikes. Good to have you here to report on issues every time!

**Comment by vincentneo** [comment]
should be fixed in beta 10. Let me know if that isn't the case for you.
