### ISSUE TITLE
Music unpauses / starts playing on its own

### ISSUE THREAD

**Issue by MasterRahool** [vincentneo/LosslessSwitcher#9]
Noticing an issue on the latest beta where music will start playing on its own

Quit the application and couldnt repeat it, enabled it again, paused a track, and it came back, so feel its related to LosslessSwitcher

- Issue appears be related to other audio playing outside of Music. It wasnt playing as I started this thread, then I played 3 seconds with Preview of a video on my desktop, when I got back to typing Music started playing my paused track again
- I tried it again, 3 seconds of desktop audio with Preview, then kill the video. A few seconds later Music starts playing.
- Repeated the above with VLC, 4 seconds of a video playing, quit VLC, Music starts playing

**Comment by vincentneo** [comment]
Yup, definitely related to this app. Previously seen it happen, and thought I patched it. Apparently not.
